# Generated by Django 2.2.6 on 2019-11-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_sale',
            field=models.BooleanField(default=False),
        ),
    ]
