# Generated by Django 2.2.6 on 2019-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_sale_percentage',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
