# Generated by Django 2.2.6 on 2019-11-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_product_sale_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='after_dicount_price',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
