# Generated by Django 2.2.6 on 2019-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_products_after_dicount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='after_dicount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_sale_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
